config/routes.rb
Rails.application.routes.draw do
  resources :activos
  resources :evaluos
  resources :tipos
  resources :detalle_sectors
  resources :sectors
  resources :encargados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/encargado.rb
class Encargado < ApplicationRecord
  #has_many :detalle_sectors
end

app/controllers/encargados_controller.rb
class EncargadosController < ApplicationController
  before_action :set_encargado, only: [:show, :edit, :update, :destroy]

  # GET /encargados
  # GET /encargados.json
  def index
    @encargados = Encargado.all
  end

  # GET /encargados/1
  # GET /encargados/1.json
  def show
  end

  # GET /encargados/new
  def new
    @encargado = Encargado.new
  end

  # GET /encargados/1/edit
  def edit
  end

  # POST /encargados
  # POST /encargados.json
  def create
    @encargado = Encargado.new(encargado_params)

    respond_to do |format|
      if @encargado.save
        format.html { redirect_to @encargado, notice: 'Encargado was successfully created.' }
        format.json { render :show, status: :created, location: @encargado }
      else
        format.html { render :new }
        format.json { render json: @encargado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encargados/1
  # PATCH/PUT /encargados/1.json
  def update
    respond_to do |format|
      if @encargado.update(encargado_params)
        format.html { redirect_to @encargado, notice: 'Encargado was successfully updated.' }
        format.json { render :show, status: :ok, location: @encargado }
      else
        format.html { render :edit }
        format.json { render json: @encargado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encargados/1
  # DELETE /encargados/1.json
  def destroy
    @encargado.destroy
    respond_to do |format|
      format.html { redirect_to encargados_url, notice: 'Encargado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encargado
      @encargado = Encargado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encargado_params
      params.require(:encargado).permit(:nombre, :telefono, :correo)
    end
end

app/helpers/encargados_helper.rb
module EncargadosHelper
end

app/views/encargados/_form.html.erb
<%= form_with(model: encargado, local: true) do |form| %>
  <% if encargado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(encargado.errors.count, "error") %> prohibited this encargado from being saved:</h2>

      <ul>
      <% encargado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :encargado_nombre %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :encargado_telefono %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :encargado_correo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/encargados/edit.html.erb
<h1>Editing Encargado</h1>

<%= render 'form', encargado: @encargado %>

<%= link_to 'Show', @encargado %> |
<%= link_to 'Back', encargados_path %>

app/views/encargados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Encargados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encargados.each do |encargado| %>
      <tr>
        <td><%= encargado.nombre %></td>
        <td><%= encargado.telefono %></td>
        <td><%= encargado.correo %></td>
        <td><%= link_to 'Show', encargado %></td>
        <td><%= link_to 'Edit', edit_encargado_path(encargado) %></td>
        <td><%= link_to 'Destroy', encargado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encargado', new_encargado_path %>

app/views/encargados/new.html.erb
<h1>New Encargado</h1>

<%= render 'form', encargado: @encargado %>

<%= link_to 'Back', encargados_path %>

app/views/encargados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @encargado.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @encargado.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @encargado.correo %>
</p>

<%= link_to 'Edit', edit_encargado_path(@encargado) %> |
<%= link_to 'Back', encargados_path %>