config/routes.rb
Rails.application.routes.draw do
  resources :activos
  resources :evaluos
  resources :tipos
  resources :detalle_sectors
  resources :sectors
  resources :encargados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/evaluo.rb
class Evaluo < ApplicationRecord
  #has_one :tipos
  #has_one :activos
end

app/controllers/evaluos_controller.rb
class EvaluosController < ApplicationController
  before_action :set_evaluo, only: [:show, :edit, :update, :destroy]

  # GET /evaluos
  # GET /evaluos.json
  def index
    @evaluos = Evaluo.all
  end

  # GET /evaluos/1
  # GET /evaluos/1.json
  def show
  end

  # GET /evaluos/new
  def new
    @evaluo = Evaluo.new
  end

  # GET /evaluos/1/edit
  def edit
  end

  # POST /evaluos
  # POST /evaluos.json
  def create
    @evaluo = Evaluo.new(evaluo_params)

    respond_to do |format|
      if @evaluo.save
        format.html { redirect_to @evaluo, notice: 'Evaluo was successfully created.' }
        format.json { render :show, status: :created, location: @evaluo }
      else
        format.html { render :new }
        format.json { render json: @evaluo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluos/1
  # PATCH/PUT /evaluos/1.json
  def update
    respond_to do |format|
      if @evaluo.update(evaluo_params)
        format.html { redirect_to @evaluo, notice: 'Evaluo was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluo }
      else
        format.html { render :edit }
        format.json { render json: @evaluo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluos/1
  # DELETE /evaluos/1.json
  def destroy
    @evaluo.destroy
    respond_to do |format|
      format.html { redirect_to evaluos_url, notice: 'Evaluo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluo
      @evaluo = Evaluo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluo_params
      params.require(:evaluo).permit(:tipo, :Activo, :integer, :descripcion, :montoactual, :fecha)
    end
end

app/helpers/evaluos_helper.rb
module EvaluosHelper
end

app/views/evaluos/_form.html.erb
<%= form_with(model: evaluo, local: true) do |form| %>
  <% if evaluo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evaluo.errors.count, "error") %> prohibited this evaluo from being saved:</h2>

      <ul>
      <% evaluo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.number_field :tipo, id: :evaluo_tipo %>
  </div>

  <div class="field">
    <%= form.label :Activo %>
    <%= form.text_field :Activo, id: :evaluo_Activo %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer, id: :evaluo_integer %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :evaluo_descripcion %>
  </div>

  <div class="field">
    <%= form.label :montoactual %>
    <%= form.text_field :montoactual, id: :evaluo_montoactual %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :evaluo_fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluos/edit.html.erb
<h1>Editing Evaluo</h1>

<%= render 'form', evaluo: @evaluo %>

<%= link_to 'Show', @evaluo %> |
<%= link_to 'Back', evaluos_path %>

app/views/evaluos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evaluos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Activo</th>
      <th>Integer</th>
      <th>Descripcion</th>
      <th>Montoactual</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluos.each do |evaluo| %>
      <tr>
        <td><%= evaluo.tipo %></td>
        <td><%= evaluo.Activo %></td>
        <td><%= evaluo.integer %></td>
        <td><%= evaluo.descripcion %></td>
        <td><%= evaluo.montoactual %></td>
        <td><%= evaluo.fecha %></td>
        <td><%= link_to 'Show', evaluo %></td>
        <td><%= link_to 'Edit', edit_evaluo_path(evaluo) %></td>
        <td><%= link_to 'Destroy', evaluo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluo', new_evaluo_path %>

app/views/evaluos/new.html.erb
<h1>New Evaluo</h1>

<%= render 'form', evaluo: @evaluo %>

<%= link_to 'Back', evaluos_path %>

app/views/evaluos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @evaluo.tipo %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @evaluo.Activo %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @evaluo.integer %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @evaluo.descripcion %>
</p>

<p>
  <strong>Montoactual:</strong>
  <%= @evaluo.montoactual %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @evaluo.fecha %>
</p>

<%= link_to 'Edit', edit_evaluo_path(@evaluo) %> |
<%= link_to 'Back', evaluos_path %>