config/routes.rb
Rails.application.routes.draw do
  resources :activos
  resources :evaluos
  resources :tipos
  resources :detalle_sectors
  resources :sectors
  resources :encargados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activo.rb
class Activo < ApplicationRecord
end

app/controllers/activos_controller.rb
class ActivosController < ApplicationController
  before_action :set_activo, only: [:show, :edit, :update, :destroy]

  # GET /activos
  # GET /activos.json
  def index
    @activos = Activo.all
  end

  # GET /activos/1
  # GET /activos/1.json
  def show
  end

  # GET /activos/new
  def new
    @activo = Activo.new
  end

  # GET /activos/1/edit
  def edit
  end

  # POST /activos
  # POST /activos.json
  def create
    @activo = Activo.new(activo_params)

    respond_to do |format|
      if @activo.save
        format.html { redirect_to @activo, notice: 'Activo was successfully created.' }
        format.json { render :show, status: :created, location: @activo }
      else
        format.html { render :new }
        format.json { render json: @activo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activos/1
  # PATCH/PUT /activos/1.json
  def update
    respond_to do |format|
      if @activo.update(activo_params)
        format.html { redirect_to @activo, notice: 'Activo was successfully updated.' }
        format.json { render :show, status: :ok, location: @activo }
      else
        format.html { render :edit }
        format.json { render json: @activo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activos/1
  # DELETE /activos/1.json
  def destroy
    @activo.destroy
    respond_to do |format|
      format.html { redirect_to activos_url, notice: 'Activo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activo
      @activo = Activo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activo_params
      params.require(:activo).permit(:descripcion, :precio, :fecha, :sector)
    end
end

app/helpers/activos_helper.rb
module ActivosHelper
end

app/views/activos/_form.html.erb
<%= form_with(model: activo, local: true) do |form| %>
  <% if activo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activo.errors.count, "error") %> prohibited this activo from being saved:</h2>

      <ul>
      <% activo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :activo_descripcion %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio, id: :activo_precio %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :activo_fecha %>
  </div>

  <div class="field">
    <%= form.label :sector %>
    <%= form.number_field :sector, id: :activo_sector %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activos/edit.html.erb
<h1>Editing Activo</h1>

<%= render 'form', activo: @activo %>

<%= link_to 'Show', @activo %> |
<%= link_to 'Back', activos_path %>

app/views/activos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Precio</th>
      <th>Fecha</th>
      <th>Sector</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activos.each do |activo| %>
      <tr>
        <td><%= activo.descripcion %></td>
        <td><%= activo.precio %></td>
        <td><%= activo.fecha %></td>
        <td><%= activo.sector %></td>
        <td><%= link_to 'Show', activo %></td>
        <td><%= link_to 'Edit', edit_activo_path(activo) %></td>
        <td><%= link_to 'Destroy', activo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activo', new_activo_path %>

app/views/activos/new.html.erb
<h1>New Activo</h1>

<%= render 'form', activo: @activo %>

<%= link_to 'Back', activos_path %>

app/views/activos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @activo.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @activo.precio %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @activo.fecha %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @activo.sector %>
</p>

<%= link_to 'Edit', edit_activo_path(@activo) %> |
<%= link_to 'Back', activos_path %>